### ISSUE TITLE
Queries Regarding Training Proxy Model and Shark ML Library Usage in Your Work

### ISSUE THREAD

**Issue by hhf-hd** [gumityolcu/DualView#9]
First and foremost, I must express my deepest admiration for your outstanding work. It is truly impressive and highly efficacious. The comprehensive documentation you've shared has made the reproduction of your results an exceptionally smooth process.

However, as I delve deeper into your methodology, I have encountered a few questions that I would humbly seek your clarification on:

May I kindly inquire about the process of training the surrogate model? Specifically, how might I generate my own checkpoint files and explanation files, similar to the ones you have so generously provided? Additionally, could you elaborate on the specific role each of these files plays in the overall framework? This aspect remains somewhat unclear to me in the current documentation.

![image](https://github.com/user-attachments/assets/3244f05e-14e7-45d6-854d-db07e3b6c3a3)
![image](https://github.com/user-attachments/assets/fb3c11cd-0898-46d6-aea7-60c9e66c7629)

In Section 5.3 of your paper, you mention utilizing the Shark ML library for pre-training purposes. Furthermore, Appendix C.1 delves into the C++ implementation of Equation 5 using Shark. I am curious to know if you have made any custom modifications to the Shark library or if the entirety of the code, excluding the pre-training segment, is fully open-source and available for public use.
I am truly grateful for your invaluable contributions to this field and the time you have dedicated to sharing your work. Your insights would be incredibly beneficial to my understanding and progress. Thank you once again for considering my questions, and I eagerly anticipate your guidance.

**Comment by gumityolcu** [comment]
Hello, we are excited to hear about your interest in DualView!

We have made minor changes in the Shark Library (we provide the whole library in /src/solvers/libs). The purpose of the modifications is to be able to reach dual variables in the underlying implementation. We also share the license associated with Shark there. TLDR: as far as i understand it allows for any use as long as you share the original license, and you release your product under a license that gives the same rights and priveleges to the user.

Then we provide a c++ program (in /src/solvers/interfaces) that uses this modified library to do the surrogate training and save trained values (weights and dual coefficients). You need to install the Shark library as we provide it. Then oyu can use the executable we have provided. Alternatively you can compile the main.cpp that we provide and save the executable as "solvers/interfaces/Shark-4.0.0/solver" as we provided in the code, or change the code to find the solver program.

To use Shark, you need CBLAS and Boost libraries for C++. In order to remedy the complication of using DualView with Shark, we are working on a modified scikit-learn based implementation. I have pushed this implementation in a seperate branch called sklearn-dualview. You can use that explainer exactly in the same manner as the Shark implementation. (Just running the project on that branch should work). However, you need to uninstall sklearn and install it using this repository:

```
  git clone git@github.com:gumityolcu/scikit-learn-dual.git
  pip install ./scikit-learn-dual
```


Please note that this implementation of dualview is a work in progress and is not thoroughly tested/evaluated. We are actively working to include results for this new wrapper (which is much more easier to use as will be explained in the documentation after we publish a second version of our paper).

Meanwhile, we are happy to provide technical support here.


I am closing the issue since i feel your questions are answered. In case you have any other questions or problems, please reach out to us again!

Best wishes
